"""Phase 3 environment-facing utilities built on frozen PvZ contracts."""

from pvz_env.observation import (
    OBSERVATION_SCHEMA_VERSION,
    OBSERVATION_SPEC,
    ObservationEncoder,
    ObservationSpec,
)
from pvz_env.actions import (
    ACTION_COUNT,
    ACTION_SCHEMA_VERSION,
    ACTION_SPEC,
    DEFERRED_ACTION_TYPES,
    MAX_SEED_SLOTS,
    PLANT_INDEX_START,
    ActionSpec,
    ActionType,
    SemanticAction,
    build_action_mask,
    decode_action,
    encode_action,
    normalize_active_rows,
)
from pvz_env.environment import (
    EnvironmentConfig,
    EnvironmentStateUnavailable,
    ObservationSnapshot,
    PvZEnvironment,
    ReconciliationStatus,
    StepRejectionReason,
    StepResult,
    StepTiming,
)
from pvz_env.logging import (
    TRANSITION_SCHEMA_VERSION,
    ArrayPayload,
    JsonlTransitionSink,
    TransitionLogFormatError,
    TransitionLoggingError,
    TransitionRecord,
    TransitionSink,
    read_transition_jsonl,
)

__all__ = [
    "OBSERVATION_SCHEMA_VERSION",
    "OBSERVATION_SPEC",
    "ObservationEncoder",
    "ObservationSpec",
    "ACTION_COUNT",
    "ACTION_SCHEMA_VERSION",
    "ACTION_SPEC",
    "DEFERRED_ACTION_TYPES",
    "MAX_SEED_SLOTS",
    "PLANT_INDEX_START",
    "ActionSpec",
    "ActionType",
    "SemanticAction",
    "build_action_mask",
    "decode_action",
    "encode_action",
    "normalize_active_rows",
    "EnvironmentConfig",
    "EnvironmentStateUnavailable",
    "ObservationSnapshot",
    "PvZEnvironment",
    "ReconciliationStatus",
    "StepRejectionReason",
    "StepResult",
    "StepTiming",
    "TRANSITION_SCHEMA_VERSION",
    "ArrayPayload",
    "JsonlTransitionSink",
    "TransitionLogFormatError",
    "TransitionLoggingError",
    "TransitionRecord",
    "TransitionSink",
    "read_transition_jsonl",
]
